### ISSUE TITLE
confused about how to edit line lengths 

### ISSUE THREAD

**Issue by pibouill** [vinicius507/ft_nvim#13]
I apologize if it is stated somewhere, I'm still struggling with lua and plugins management 

But I can't find the option to reduce/modify lines length anywhere (without breaking the plugin that is and having Lazy screaming at me)

Thanks in advance and thanks for the works

**Comment by vinicius507** [comment]
Greetings, @pibouill!

What do you mean by line length? The header line length?
Or are you talking about the line length limit set by the norme?

Thanks :)

**Comment by pibouill** [comment]
Sorry for lack of details

Yes, I'm talking about the header's login / email line length

Since my email address is pretty long, that line goes one extra character and makes the line go over the 80 col limit
(at least that's what I was assuming)

![example](https://github.com/user-attachments/assets/7ff6ba4f-4a6f-4b57-88b8-8469c11b7365)

**Comment by vinicius507** [comment]
Yeah, definitely a bug.

I'll check it out later today. :)

**Comment by vinicius507** [comment]
Greetings, @pibouill, sorry for the delay.

Would it be a problem if your email were to be ellipsized?

**Comment by pibouill** [comment]
Hey, no worries!

No, it wouldn't be an issue at all
If I'm not mistaken, I think this is actually the default behavior of stdheader in the first place :D 

Thanks a lot

**Comment by vinicius507** [comment]
Great. For now I increased the template line length by 1, which should already fix your issue.

I'll work on truncating the email later this week I'll close this issue when that's done.

Thanks a ton :)
